title: Ruochen's Blog
email: sc16rl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carrotsniper.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Ruochen Li # add your name
author-pic: adam-face.jpg
about-author: My name is Ruochen Li, I am currently a 1st year Phd student at Durham University

# Contact links
email: blsz22@durham.ac.uk
phone: (+44)7541591080
linkedin: # Add your Linkedin handle
github: CarrotSniper # Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
